### ISSUE TITLE
Failed to execute: javax.ws.rs.NotFoundException

### ISSUE THREAD

**Issue by zappoi** [Doccrazy/keycloak-protocol-cas#6]
Hi,
With keycloak-3.2.0 final in standalone mode I have this exception when I try to reach the CAS url:
Could not find resource for full path: https://XXX.XXX.XXX/auth/realms/master/protocol/cas

**Comment by zappoi** [comment]
`2017-07-24 11:48:45,241 ERROR [org.jboss.resteasy.resteasy_jaxrs.i18n] (default task-11) RESTEASY002010: Failed to execute: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: https://XXX.XXX.XXX/auth/realms/demo/protocol/cas
	at org.jboss.resteasy.core.registry.SegmentNode.match(SegmentNode.java:114)
	at org.jboss.resteasy.core.registry.RootNode.match(RootNode.java:43)
	at org.jboss.resteasy.core.LocatorRegistry.getResourceInvoker(LocatorRegistry.java:79)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:129)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:395)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:202)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:221)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.services.filters.KeycloakSessionServletFilter.doFilter(KeycloakSessionServletFilter.java:90)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:174)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:793)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by Doccrazy** [comment]
Thanks for your bug report! I did not yet get to testing the CAS plugin against Keycloak 3.2.0, so some issues are to be expected.

I will look into this as soon as i find the time.

**Comment by zappoi** [comment]
Okay thanks ! Tell me if I can help !

**Comment by Doccrazy** [comment]
Keycloak 3.2 introduced some backwards-incompatible changes that required an update of the plugin. I pushed the changes to branch feature-keycloak-3.2 and tested them locally.  
However, it would be very helpful if you could test the plugin in your installation and report your result.

I also released version 2.0.0-beta.0 that contains the changes, so you don't have to compile it yourself 😉 
https://github.com/Doccrazy/keycloak-protocol-cas/releases/tag/2.0.0-beta.0

**Comment by zappoi** [comment]
Hello,
same error with the last version :-(
I also have this warning:

`2017-09-04 16:31:08,124 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-p
rotocol-cas-2.0.0-beta.0.jar" is using a private module ("org.keycloak.keycloak-server-spi-private:main") which may be changed or remov
ed in future versions without notice.
2017-09-04 16:31:08,124 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-p
rotocol-cas-2.0.0-beta.0.jar" is using a private module ("org.keycloak.keycloak-services:main") which may be changed or removed in futu
re versions without notice.
2017-09-04 16:31:08,124 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-p
rotocol-cas-2.0.0-beta.0.jar" is using a private module ("org.keycloak.keycloak-saml-core:main") which may be changed or removed in fut
ure versions without notice.
2017-09-04 16:31:08,124 WARN  [org.jboss.as.dependency.private] (MSC service thread 1-1) WFLYSRV0018: Deployment "deployment.keycloak-p
rotocol-cas-2.0.0-beta.0.jar" is using a private module ("org.keycloak.keycloak-saml-core-public:main") which may be changed or removed
 in future versions without notice.`

**Comment by Doccrazy** [comment]
Are you running the release candidate version 3.3.0.CR1 of Keycloak? This is a preview release, and the plugin has not yet been updated. I will try to look into it soon, but no promises ;) .

I suggest you stick with 3.2.1 for now, which should be working (in fact, we are running it in production in our company).

The warnings you mentioned are normal, as the plugin has to use internal parts of the OpenIDC implementation to avoid insane amounts of code duplication. This is unfortunate, but for now unavoidable.

**Comment by zappoi** [comment]
No I'm running the 3.2.1... I start an installation from scratch, I copy the .jar you provid in standalone/deployments but I get the error I paste below... :/
Maybe I should forget some parameters ?

**Comment by Doccrazy** [comment]
I just tested with a clean install of 3.2.1 and could not reproduce the issue, everything seems to be working.

There should be no configuration necessary, beside creating a client with the proper redirect URI in the admin UI. Do you see the cas entry in the "Client Protocol" dropdown there?

If possible, could you PM me the full log of your installation?

**Comment by zappoi** [comment]
My bad ! I forgot on parameter, works fine  now ! 
Thanks a lot for your patience & fast replie !
